### ISSUE TITLE
Different test behaviour locally compared to GitHub Actions

### ISSUE THREAD

**Issue by dsgibbons** [dsgibbons/shap#30]
I have a couple of tests failing locally that doesn't fail in GitHub Actions: 

- `tests.explainers.test_exact::test_tabular_single_output_partition_masker`
- `tests.explainers.test_exact::test_tabular_multi_output_partition_masker`

In both cases, the problem is line 281 from `shap.explainers._exact` inside the `partition_masks` function:

```python
return all_masks[order], np.array([[np.array(on), np.array(off)] for on,off in inds_lists])
```

which raises 
```
*** ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (12, 2) + inhomogeneous part.
```

I'm not sure how this doesn't raise an error in GitHub Actions. I'm using Python 3.10.6 and `np.__version__==1.24.3`. Has anyone else observed this?

**Comment by thatlittleboy** [comment]
Seems like on GH Actions, it's a warning, not an error. Which is why the test passes.

![image](https://github.com/dsgibbons/shap/assets/30731072/fe9d1b6b-0618-4847-9963-8e4ad1db40cf)

Not sure why though, I can take a look over the weekend. Could be some dependency differences.

**Comment by dsgibbons** [comment]
Oh interesting, makes sense! GitHub Actions must use an older version of `numpy` before the deprecation was converted to an error.

**Comment by connortann** [comment]
I think a more broad error is that we don't have pinned versions of dependencies, so we don't have a very stable set of tests.

In most circumstances, I'd recommend migrating to python poetry as it's a really fantastic way of managing dependencies and updates. However, that's probably not a good idea here (at least for now), as it would involve a really big change to the packaging process.

How could we start - perhaps by defining a `requirements.txt` or `requirements-dev.txt` that specifies pinned versions of dependencies used for tests?

**Comment by thatlittleboy** [comment]
I've found out why the discrepancy is happening.

* GH actions' numpy version is 1.23.5 when running tests (at least, for py3.8+), which emits a warning instead of an error about the inhomogeneous shape. The error is emitted on numpy 1.24+)
* The reason why GH actions' numpy is not 1.24 is because of the installation of tensorflow v2.12.0 (I suspect, @dsgibbons didn't install tensorflow locally) , which has an upper bound dependency on numpy <1.24.

<img src="https://github.com/dsgibbons/shap/assets/30731072/fddc04d7-aea8-42e8-812b-ff1dd2f3a2d7" width=500>



So I don't think pinning test dependencies will solve the issue here (though, whether we should do so, is a different topic altogether). The more important thing is to ensure the environment setup is consistent both locally and on GH.  

I'll address this in my next PR (incorporate the installation of tensorflow directly inside the optional test dependencies).

**Comment by dsgibbons** [comment]
Correct, I installed via `pip install -e .[test]` so `tensorflow` wouldn't have been included given current `setup.py`. Thanks @thatlittleboy for sorting this out.
